USE [AmazonReviewsDWH]
GO

/****** Object:  View [dbo].[v_dimDate]    Script Date: 5/17/2021 10:27:20 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[v_dimDate] AS


SELECT *
    ,[IsWeekDay]			= CASE WHEN DATEPART(WEEKDAY,[Date]) <= 5 THEN 'Yes' ELSE 'No' END
    ,[IsWeekend]			= CASE WHEN DATEPART(WEEKDAY,[Date]) >= 6 THEN 'Yes' ELSE 'No' END
    ,[DayNumber]			= DATEPART(WEEKDAY,[Date])
	,[Today]				= CASE WHEN CONVERT(DATE,GETDATE()) = CONVERT(DATE,[Date]) THEN 'Yes' ELSE 'No' END
	,[CurrentMonth]			= CASE WHEN MONTH([Date]) = MONTH(CONVERT(DATE,GETDATE())) THEN 'Yes' ELSE 'No' END
	,[CurrentYear]			= CASE WHEN YEAR([Date]) = YEAR(CONVERT(DATE,GETDATE())) THEN 'Yes' ELSE 'No' END
	,[Yesterday]			= CASE WHEN [Date] = DATEADD(DAY,-1,CONVERT(DATE,CONVERT(DATE,GETDATE()))) THEN 'Yes' ELSE 'No' END
	,[LastWeek]				= CASE WHEN [Date] BETWEEN DATEADD(WEEK,DATEDIFF(WEEK,6,CONVERT(DATE,GETDATE())),0) AND DATEADD(WEEK,DATEDIFF(WEEK,6,CONVERT(DATE,GETDATE())),6) THEN 'Yes' ELSE 'No' END
	,[LastMonth]			= CASE WHEN [Date] BETWEEN DATEADD(DAY,1,EOMONTH(CONVERT(DATE,GETDATE()),-2)) AND EOMONTH(CONVERT(DATE,GETDATE()),-1) THEN 'Yes' ELSE 'No' END
	,[LastYear]				= CASE WHEN YEAR([Date]) = YEAR(CONVERT(DATE,GETDATE())) - 1 THEN 'Yes' ELSE 'No' END
	,[Period]				= CASE WHEN [Date] > CONVERT(DATE,GETDATE()) THEN 'Future' ELSE 'Past' END
	,[Last30Days]			= CASE WHEN [Date] BETWEEN DATEADD(DAY,-30,CONVERT(DATE,GETDATE())) AND CONVERT(DATE,GETDATE()) THEN 'Yes' ELSE 'No' END
	,[Last60Days]			= CASE WHEN [Date] BETWEEN DATEADD(DAY,-60,CONVERT(DATE,GETDATE())) AND CONVERT(DATE,GETDATE()) THEN 'Yes' ELSE 'No' END
	,[Last3Months]			= CASE WHEN [Date] BETWEEN DATEADD(DAY,1,EOMONTH(CONVERT(DATE,GETDATE()),-4)) AND EOMONTH(CONVERT(DATE,GETDATE())) THEN 'Yes' ELSE 'No' END
	,[Last6Months]			= CASE WHEN [Date] BETWEEN DATEADD(DAY,1,EOMONTH(CONVERT(DATE,GETDATE()),-7)) AND EOMONTH(CONVERT(DATE,GETDATE())) THEN 'Yes' ELSE 'No' END
	,[Last12Months]			= CASE WHEN [Date] BETWEEN DATEADD(DAY,1,EOMONTH(CONVERT(DATE,GETDATE()),-13)) AND EOMONTH(CONVERT(DATE,GETDATE())) THEN 'Yes' ELSE 'No' END
	,[Last3Years]			= CASE WHEN YEAR([Date]) BETWEEN YEAR(CONVERT(DATE,GETDATE())) - 3 AND YEAR(CONVERT(DATE,GETDATE())) THEN 'Yes' ELSE 'No' END
	,[CurrentWeek]			= CASE WHEN DATEPART(iso_week,[Date]) = DATEPART(iso_week,CONVERT(DATE,GETDATE())) AND YEAR([Date]) = YEAR(CONVERT(DATE,GETDATE())) THEN 'Yes' ELSE 'No' END
	,[Last12Weeks]			= CASE WHEN [Date] BETWEEN DATEADD(WEEK,DATEDIFF(WEEK,6,CONVERT(DATE,GETDATE()))-11,0) AND DATEADD(WEEK,DATEDIFF(WEEK,6,CONVERT(DATE,GETDATE()))+1,6) THEN 'Yes' ELSE 'No' END
	,[Last6Weeks]			= CASE WHEN [Date] BETWEEN DATEADD(WEEK,DATEDIFF(WEEK,6,CONVERT(DATE,GETDATE()))-5,0) AND DATEADD(WEEK,DATEDIFF(WEEK,6,CONVERT(DATE,GETDATE()))+1,6) THEN 'Yes' ELSE 'No' END
FROM dimDate
GO


